### Update genre
PATCH http://localhost:8080/api/genres/1
Content-Type: application/json

{
  "name": "ActionUpdated"
}

### Change back
PATCH http://localhost:8080/api/genres/1
Content-Type: application/json

{
  "name": "Action"
}


### Update actor
PATCH http://localhost:8080/api/actors/1
Content-Type: application/json

{
  "name": "tom hanks",
  "birthDate": "1956-07-09",
  "movies": [
    1,
    {
      "id": 2
    }
  ]
}


### Update movie
PATCH http://localhost:8080/api/movies/1
Content-Type: application/json

{
  "title": "Inception",
  "releaseYear": 2010,
  "duration": 148,
  "genres": [
    {
      "id": 2
    },
    5
  ],
  "actors": [
    {
      "id": 3
    },
    8
  ]
}

